export const GET_ONE_TODO_SUCCESS = "GET_ONE_TODO_SACCESS"
export const GET_ONE_TODO_FAIL = "GET_ONE_TODO_FAIL"
export const GET_ALL_TODOS_SUCCESS = "GET_ALL_TODOS_SACCESS"
export const GET_ALL_TODOS_FAIL = "GET_ALL_TODOS_FAIL"